services:

  tests:
    image: eclipse-temurin:21-jdk

    working_dir: /app

    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal

    command:
      - sh
      - -c
      - |
        chmod +x mvnw
        ./mvnw clean verify
