app.bootstrap.admin.enabled=true
logging.level.org.flywaydb=DEBUG

app.bootstrap.admin.email=${ADMIN_EMAIL}
app.bootstrap.admin.password=${ADMIN_PASSWORD}


app.security.csrf-enabled=false

spring.jpa.open-in-view=false
