name: Auto Pull & Restart Spring

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, win-dev]

    steps:
      - name: Pull latest code
        shell: powershell
        run: |
          cd C:\uop
          git pull

      - name: Kill old Spring
        shell: powershell
        run: |
          Get-Process java -ErrorAction SilentlyContinue | Stop-Process -Force
      - name: Run Spring detached
        shell: powershell
        run: |
          Start-Process powershell.exe `
            -ArgumentList "-NoExit", "-Command", "cd C:\uop; `$Host.UI.RawUI.WindowTitle='SpringApp'; mvn spring-boot:run" `
            -WindowStyle Normal

          while ($true) {
            if (Test-NetConnection localhost -Port 8080 -InformationLevel Quiet) {
              Start-Sleep -Seconds 5
            }
            else {
              exit 0
            }
          }
