name: Auto Pull & Restart Spring
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, win-dev]
    steps:
      - name: Pull latest code
        shell:  powershell

        run: |
          cd C:\uop
          git pull

      - name: Kill old Spring window
        shell: powershell

        run: |
          Get-Process powershell | Where-Object { $_.MainWindowTitle -eq "SpringApp" } | Stop-Process -Force

      - name: Run new Spring with mvn spring-boot:run
        shell: powershell
        run: |
          cd C:\uop
          Start-Process powershell -ArgumentList "-NoExit", "-WindowStyle Normal", "-Command", "`$Host.UI.RawUI.WindowTitle = 'SpringApp'; mvn spring-boot:run"
