name: Auto Pull & Dev Deploy

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: [self-hosted, win-dev]

    steps:
      - name: Pull latest code
        shell: powershell
        run: |
          cd C:\uop
          git pull --ff-only

      - name: Run tests
        shell: powershell
        run: |
          cd C:\uop

          docker compose -f docker-compose.test.yml run --rm tests

          if ($LASTEXITCODE -ne 0) {
            Write-Error "Tests failed"
            exit $LASTEXITCODE
          }
  devwindowsdeploy:
    needs: tests
    runs-on: [self-hosted,win-dev]

    steps:
      - name: Rebuild and restart containers
        shell: powershell
        run: |
          cd C:\uop
          $env:SPRING_PROFILES_ACTIVE="dev"
          docker compose down -v
          docker compose up -d --build
      - name: Wait for application
        shell: powershell
        run: |
          $maxAttempts = 100 
          for ($i = 0; $i -lt $maxAttempts; $i++) {

          if (Test-NetConnection localhost -Port 8080 -InformationLevel Quiet) { 
            Write-Host "Application is ready" 
            exit 0 
          }

            Start-Sleep -Seconds 5 
          } 
          Write-Error "Application failed to start" 
          docker compose logs 
          exit 1
